### ISSUE TITLE
Feature request: Customize notification icon

### ISSUE THREAD

**Issue by Tediore** [gotify/android#116]
Really liking gotify, thanks for this! It would be nice to be able to customize the icon displayed in the notification bar. Any thoughts?

**Comment by jmattheis** [comment]
I don't think this is really necessary, thus, I'm waiting for more feedback.

**Comment by Tediore** [comment]
Perhaps a better way of explaining my request would be adding an option for the notification icon to match the custom icon that you can set for the applications you define in gotify server.

**Comment by jmattheis** [comment]
There is most certainly a way for this. But I don't know if the developments costs cover the actual need for this feature.

**Comment by Tediore** [comment]
Understood! Thanks for your consideration. If you do get around to it, I'd be happy to help with any testing.

**Comment by PanderMusubi** [comment]
See also https://github.com/gotify/android/issues/196

**Comment by itkfilelor** [comment]
[Join](https://joaoapps.com/join/) notifications have this capability. the icon and smallicon fields are populated with a locally (to the target device) accessable icon/png file or a pubilically available via a web url.
It also has the capability to create custom categories to allow custom notification behavior per app.

**Comment by jmattheis** [comment]
Closing as not needed as there aren't many upvotes or comments from other users.

**Comment by iankaufmann** [comment]
I am not a user of gotify (yet), but I am shopping around for an alternative to Pushover.  This is the feature I am looking for, and it seems none of the options, including Pushover will support this.

To me, it seems completely necessary to be able to customize this status bar icon.  If you have notifications from many different things of differing context or importance, being able to see at a glance what the notification is related to would be so helpful.  Right now, when I see that little "P" for Pushover in the status bar, my first thought is "oh no".  It could be a critical issue, or it could be Sonarr telling me some show just downloaded.  

I just wanted to mention that Home Assistant allows this functionality, and they do it by letting you choose a material design icon when sending a notification, and it works great.  My camera notifications get a camera icon, mail delivery gets a mailbox icon, etc.  It's such a great touch.

You might now be asking, why not just use HA for all notifications?  Well, Pushover has always served as a backup.  If I were to self-host something like gotify, I'd put it on a cloud VPS.  HA is great, but I there are some notifications I don't want to rely on my home internet being up, and I don't want to be afraid to reboot HA and miss something.  I also use Pushover in many places that are not able to access my HA server.

I'm not expecting anyone to do anything, but I came across this thread and just wanted to say something.  I'm kind of shocked that this isn't a bigger issue with more engagement.  I don't know if I'll bother setting this up without this feature, because it's the only reason I really want to move off of Pushover.

**Comment by PanderMusubi** [comment]
Have also a look at https://github.com/binwiederhier/ntfy-android

**Comment by iankaufmann** [comment]
> Have also a look at https://github.com/binwiederhier/ntfy-android

As far as I could tell, the only documentation regarding "icons" is not the status bar icon but an image inside of the notification after you open it:  https://docs.ntfy.sh/publish/#icons

It's pretty much exactly the same as how Pushover handles it as well.

Unless I'm missing something, I think ntfy has the same issue.

**Comment by RavingGrob** [comment]
While it wouldn't necessarily solve for the white/black silhouetted icons, there appears to be a way to change the main icon to at least display the topic/conversations's icon. The Matrix Client *Commet* for example does this:

 
![Image](https://github.com/user-attachments/assets/ed05b729-de0d-4bb7-b1ba-e4f9469e9ebe)
![Image](https://github.com/user-attachments/assets/daf0aa7c-ab03-4df8-96f0-93d1f9a68c9e)

I think it's a good solution to simplify the look of the notifications, and  not obscure that it's a notification provided by Gotify.
