### ISSUE TITLE
Support multiple languages & Remember the server address

### ISSUE THREAD

**Issue by fcwys** [gotify/android#199]
1、Support multiple languages
2、Remember the server address, which can be selected from the drop-down box

**Comment by jmattheis** [comment]
1. See https://github.com/gotify/android/issues/176#issuecomment-850521464
2. Could be done, but I don't think this is a heavily used feature, thus, I think it is not worth the development effort.

**Comment by ptdev** [comment]
Hey there,

Sorry for adding to a closed issue.

But remembering the last server URL on the login screen would be very useful because we logout when we don't wish to receive more notifications, but when trying to login again, we have to type the full server url every time.

Simply remembering the last URL and keeping it on the input field when reopening the app would already by very useful. 
 Wouldn't even really need any dropdown or anything (unless you then wanted to remember multiple servers).

Just my 2 cents. 

Cheers and thanks for the work done on this project, it's very useful 👍

**Comment by jmattheis** [comment]
@ptdev, there are two other options to get your wanted behavior without logging out.
1. Force stop the app. Notifications will appear after opening the app again
2. Disable notifications of the app in the notification settings. Have to be enabled again, to receive notifications.
