### ISSUE TITLE
Critical Alert

### ISSUE THREAD

**Issue by wuast94** [gotify/android#216]
Dont know if its possible on android but on IOS there is a very high priority push level,
it ignores everything and vibrates and play sound, no matter if its on mute or do not disturb or anything else. 

Would love to see this on android here, i found something from HomeAssistant, if i understand it right they are using alarm strema that ignores dnd or muted etc and have even an option to set the volume to max. they use some TTS tricks so they know when an alarm gets played and restore volume after that. Here are useful links i found and hope it helps. 

https://github.com/home-assistant/android/blob/d0842ab55718dea104c5d959a11541bc3d586a4a/app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt

https://companion.home-assistant.io/docs/notifications/critical-notifications/#android-alarm-stream

https://github.com/home-assistant/android/issues/1166#issuecomment-723597951

would love to see this feature on gotify. having prioritys is a nice thing but when my phone only vibrates on a high prio notification becouse its muted ... you know what i mean

**Comment by jmattheis** [comment]
DND can be overridden in the [android notification settings](https://user-images.githubusercontent.com/14895212/156935532-89772e8d-8828-4163-808a-93ce28858622.png). I think this can be included into https://github.com/gotify/android/issues/203 right?

**Comment by Canopyultra** [comment]
I'm not sure this is the same. #203 talks about an ongoing notification such as a phone call. Here the request is to play a sound even if the phone is in silent mode.

In android this can be accomplished using the alarm stream (as homeassistant does, see link in the first post). 

So the request is: can an alarm stream be configured? This is different from overriding the DND system. Overriding DND is not very useful on Android since it does not override silent mode.
