### ISSUE TITLE
No sound when connection is lost and restored

### ISSUE THREAD

**Issue by PanderMusubi** [gotify/android#264]
Can an option be added that the app is not giving a sound notification when connection is lost or restored? When switching often from networks this then gives an unneeded sound notification which draws attention to the user and others. Implementing this will make the app nicer to use.

**Comment by PanderMusubi** [comment]
An alternative implementation is to offer the user to choose the priority of these notifications.

**Comment by jmattheis** [comment]
Normally the app shouldn't make sound, what android version does your phone have?

**Comment by PanderMusubi** [comment]
A device from OnePlus with LineageOS 18 that has Android 11. I can recheck next week when I have upgraded to LineageOS 19 with Android 12 and report bacl..

**Comment by jmattheis** [comment]
you can mute the foreground notification, then there should be no sound.

**Comment by PanderMusubi** [comment]
Yes, managed to disable it in Android 11.

**Comment by PanderMusubi** [comment]
Alternatively, some clear instruction could be added inside the app to help the user with this.

**Comment by jmattheis** [comment]
On my stock android phone, the foreground notification / notifications about connection change are silent per default. 
There are tickets from users that want a notification when the connection status changed, so I think your problem is not common -> https://github.com/gotify/android/issues/219 I think there are also some more tickets about this, but I'm too lazy to look them up.
