### ISSUE TITLE
Gotify requires pernissions to display push notifications

### ISSUE THREAD

**Issue by 7h3ju57** [gotify/android#293]
Hello, gotify app and server have been working for quite some ti e now but recently, the app hasn't been working. When I launch the app I get a message of gotify requires permissions which I've enabled everything I can think of but won't let me move forward .
I can register the server, it creates the client but then gives me the permissions error.

Could this have anything to do with android beta? I'm running upsidedowncake UPB2.230407.014

Hope you can help.

**Comment by jmattheis** [comment]
I can reproduce this with an android 14 emulator. Looks like the permission check is faulty or something related to this. After removing this line
https://github.com/gotify/android/blob/d22184b52fd03719afa79383dea546302baa8e09/app/src/main/kotlin/com/github/gotify/init/InitializationActivity.kt#L161
it seems to work. Tho, this may still break things because there are changes related to scheduled exact alarms in android 14 https://developer.android.com/about/versions/14/changes/schedule-exact-alarms

Exact scheduling is currently used to automatically reconnect after the connection is lost.

**Comment by 7h3ju57** [comment]
Pr works for me so far
