### ISSUE TITLE
Less intrusive notification 

### ISSUE THREAD

**Issue by jkaberg** [gotify/android#30]
IMO the current notification is way to intrusive for its purpose (to keep the app "online"), I know other apps make use of another type of smaller ("system"?) notification which is only shown when you pull down the notification drawer (and otherwise is hidden on lock screen etc.)

Would it be feasible to migrate to this?

**Comment by jmattheis** [comment]
AFAIK, it isn't possible to configure this in app code. When IMPORTANCE_LOW is used, Android changes it to a notification with a higher importance:
> Min notification importance: only shows in the shade, below the fold. This should not be used with Service.startForeground since a foreground service is supposed to be something the user cares about so it does not make semantic sense to mark its notification as minimum importance. If you do this as of Android version O, the system will show a higher-priority notification about your app running in the background.

https://developer.android.com/reference/android/app/NotificationManager.html#IMPORTANCE_MIN

You can however configure it manually. 
* Settings -> Apps -> Gotify
* Click Notifications
* Click on `Gotify foreground notification`
* Select different "Behavior" or "Importance" (depends on your android version) which uses a minimized notification
* Restart Gotify

**Comment by jmattheis** [comment]
I agree, that the status-notification should be minimized, if you know a way how to do it feel free to write it here (:.

I'm pretty sure because it is written in the official android docs.
I did the following change and the foreground notification still wasn't minimized (I'm using android pie). (this was expected, see https://github.com/gotify/android/issues/30#issuecomment-444237631)
``` diff
diff --git a/app/src/main/java/com/github/gotify/NotificationSupport.java b/app/src/main/java/com/github/gotify/NotificationSupport.java
index fdd34df..a792d42 100644
--- a/app/src/main/java/com/github/gotify/NotificationSupport.java
+++ b/app/src/main/java/com/github/gotify/NotificationSupport.java
@@ -30,17 +30,17 @@ public class NotificationSupport {
             NotificationChannel foreground =
                     new NotificationChannel(
                             Channel.FOREGROUND,
                             "Gotify foreground notification",
-                            NotificationManager.IMPORTANCE_LOW);
+                            NotificationManager.IMPORTANCE_MIN);                                                                                                               
```


Messages with `priority < 1` are minimized and use this channel:
https://github.com/gotify/android/blob/777dd081d3d9165fa730fb123bf6da8982862fd0/app/src/main/java/com/github/gotify/NotificationSupport.java#L40-L44

Are you sure that Tasker is using a foreground service?

**Comment by schwma** [comment]
I also have a stock Samsung Galaxy S8 running Oreo (8.0.0) and changing `IMPORTANCE_LOW` to `IMPORTANCE_MIN` actually did make the foreground notification less intrusive. But only after completely reinstalling Gotify. I had the same problem when making my other notification changes since Android saves the notification settings across updates. Did you try uninstalling Gotify before testing your changes @jmattheis ?

**Comment by jmattheis** [comment]
@schwma Jup, I did, tho I have Android Pie (9.0.0) so maybe it does work for android 8.

**Comment by jkaberg** [comment]
@jmattheis So obviously I'm no android dev, but I'm asking myself; how does Whatsapp, Signal etc do this? They don't even have an notification?

**Comment by ialokim** [comment]
Please see #33 for an attempt to restrict the notification on older devices.

> So obviously I'm no android dev, but I'm asking myself; how does Whatsapp, Signal etc do this? They don't even have an notification?

@jkaberg They are using [Firebase Cloud Messaging](https://firebase.google.com/docs/cloud-messaging/) and because this is integrated in the so-called and always preinstalled "Google Play Services" and Android is developed by Google, they do allow their own foreground service to be run without notification.

Messenger (and many other apps btw) then only have to send a request to the Google servers, and they will wake up the user's phone to display the notification.

**Comment by jmattheis** [comment]
I'm closing this for now. AFAIK it is not possible to make the foreground notification less intrusive as it is now.
