### ISSUE TITLE
Swipe to remove messages

### ISSUE THREAD

**Issue by wahlis** [gotify/android#38]
It would be great if the messages could be removed by swiping

**Comment by adarazs** [comment]
I could imagine an actionable button like "Mark Read" or "Delete" instead of swyping away equaling deleting the message, but I wouldn't mind the original suggestion either.

As an addition to this, it would make the experience a lot smoother if there would be a two way sync between removing the messages on Android and the WebUI, i.e.:

1. Swiping away the message would both delete the notification and refresh the view on the WebUI. (It already updates immediately when it gets a new one, it should also update when one is deleted from the backend.)
1. Deleting the message in the WebUI would dismiss the notification on the Android clients. (I like to keep the WebUI open to get notifications on desktop and would be helpful if I could de-clutter my phone of already seen notifications.)

**Comment by leopoldsedev** [comment]
I'm gonna try to implement this tomorrow.
Message synchronization is being discussed in https://github.com/gotify/server/issues/266.
