### ISSUE TITLE
View precise timestamp

### ISSUE THREAD

**Issue by Leosirth** [gotify/android#90]
Hi,

I would like to be able to view the precise timestamp for a received notification from the android application.
Currently on the application it's only visible how long ago a notification has been received i.e.:

4 hours ago

The same behavior can be observed on the webUI, but hovering the mouse on the time, the full timestamp is shown.
I would like to have the same information on the application.

Thanks and regards,

**Comment by jmattheis** [comment]
Looks like a good addition!

**Comment by x-jokay** [comment]
Just wanted to create an issue for this now (for the client-side) of the server issue https://github.com/gotify/server/issues/258 :wink:

**Comment by pm-pm** [comment]
I was thinking about the Problem ... and found no Problem. ;-) I have always the timestamp on my Android Client. :-)

I add the current timestamp as part of my title/message. (Assumption: Tx and Rx immediately)

Personally the Information "2 days ago" makes it more easy to delete old Messages instead of thinking which date was yesterday. - But i understand your Intention. :-)

Maybe you can use my idea as workaround?

**Comment by x-jokay** [comment]
@pm-pm yes, this is an idea but it would be better to send the time information only once and having the choice in the settings.
I prefer a clean `title` and `message`, especially on a smaller smartphone screens.

**Comment by Leosirth** [comment]
Hi @pm-pm 

I understand that adding the information on the notification itself could resolve the issue but looks like a workaround in my opinion.

I think it would be nice for all to have an option in order to switch from precise timestamp and time ago.
This information is already part of the notification technical payload and asking the application to add the same on the body is redundant in my opinion.

Thanks and regards,
